### ISSUE TITLE
How can I configure chainWebpack on developing theme?

### ISSUE THREAD

**Issue by yuchanns** [vuepress/vuepress-next#14]
## Question
Since the chainWebpack on PluginApi removed, is there any way to configure it on developing theme? Actually what I want is to enable jsx-next for vuepress-next

**Comment by meteorlxy** [comment]
It's removed from plugin API because we want to decouple with webpack. It's still available in user config: `bundlerConfig.chainWebpack`.

Optional choices:

1. Provide a util function for theme users to set `bundlerConfig.chainWebpack` in their config file.

2. Pre-compile your theme files, so users do not need to compile them again when developing / building, which will speed up your theme.

We are planning to implement the second one in default theme.

> A known issue is that, the `layouts` directory of your theme only accept `.vue` files for now. We'll modify the layout resolving in alpha stage.

**Comment by meteorlxy** [comment]
BTW, we have migrated to esbuild-loader, and the `tsx` support is enabled. But it has not been tested.

**Comment by meteorlxy** [comment]
https://github.com/vuepress/vuepress-next/blob/main/docs/reference/bundler/webpack.md#chainwebpack
