### ISSUE TITLE
[Feature request] Mutiple action buttons on homepage

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#23]
## Feature request

I am sure a few people wants muti action button support in the vuepress repo. https://github.com/vuejs/vuepress/issues/2261

I am having this feature in my own theme, and I saw my users are using it.

### Proposed Solution

```yml
actions:
  - link: link1
    text: text1
  - link: link2
    text: text2 
```

I am willing to send a PR if you think it's fine.

**Comment by meteorlxy** [comment]
A more flexible way:

Encourage users to customize their own home page via custom layout.

This kind of minimal features on default theme is endless...

**Comment by meteorlxy** [comment]
When you visit a website, you might immediately realize that it was developed by vuepress because of the homepage.

---

VitePress considered removing the homepage feature totally in its default theme. I think it's kind of a good idea, but we must consider some tradeoff:

**Pros**

Homepage of default theme is dull and makes lots of site look similar with each other. Removing default homepage might make those websites more diverse.

**Cons**

The default homepage is convenient indeed, allowing lots of simple sites to have a homepage that looks good.

---

So maybe we could:

- Still provide the default homepage.
- If the default homepage is not enough, encourage users to use custom homepage, and provide a detailed guide for that.
- If the default theme is not enough, encourage users to use community theme for more features.

---

As a VuePress maintainer / contributor, what we need to consider is different from a theme author. What do you think about that 🤔

**Comment by Mister-Hope** [comment]
> A more flexible way:
> 
> Encourage users to customize their own home page via custom layout.
> 
> This kind of minimal features on default theme is endless...

I totally agree with above comment, but not this one.

I was taking attention to all the issues between 20 Mar and 20 Oct, and I think this is a feature metioned by most people.

I do agree that something like sponser support, darkmode and so on don't need to provide with the default theme. But it's really common to have mutiple entries for a doc site. There are a lot of users using vuepress just has a simple doc generater (And that's the original goal when uliuz start this project). So I would more regard this feature has a helpful one, which can imporve the experience for those using vuepress as a simple doc generator.

![image](https://user-images.githubusercontent.com/33315834/103432971-cb453500-4be0-11eb-88eb-88dd0ff64a42.png)

![Uploading image.png…]()

**Comment by meteorlxy** [comment]
VuePress was created by Evan 😅

**Comment by meteorlxy** [comment]
What about a `type` field for different button style?

```
actions:
  - link: link1
    text: text1
    type: primary
  - link: link2
    text: text2
    type: secondary
```
