### ISSUE TITLE
[Feature request] Auto generating manifest in pwa plugins

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#24]
## Feature request

I would like to ship a feature to auto generating manifest to the official pwa plugin.  That would add support for installing it on desktops or mobile phones as an app.

### Description

See https://vuepress-pwa.mrhope.site/guide/#manifest for description
And https://vuepress-pwa.mrhope.site/config/#manifest for fallbacks.

If you think it's a nice feature, I will ship this feature to the official plugin.

Besides, I think it would be nice if the official plugin can have some simple options configuring the service worker. ( The request came from my users)

https://vuepress-pwa.mrhope.site/guide/#cache-size

I am looking forward for your opinion towards it.

**Comment by meteorlxy** [comment]
All options of workbox-build are already supported. You should check out our current implementation first before commiting a FR.

As for the manifest, it's OK to help generating manifest file, but it looks like that it just move those manifest fields from `manifest.json` to `.vuepress/config.js`, which does not make much sense.

IMO, Providing a detailed guide is more important, because users still have to create icons, choose colors, etc. by themselves.
