### ISSUE TITLE
[Feature request] Give access to extended page data in plugins

### ISSUE THREAD

**Issue by Demivan** [vuepress/vuepress-next#319]
### Description

I wanted to write sitemap plugin and wanted to access page updated time from `git` plugin in `onGenerated` hook. But there is no easy way to access page data after it was extended.

### Proposed Solution

In `preparePageData` assign extended data back to `page` or `page.extendedData`. This will allow access to extended data in `onPrepared` and `onGenerated` hooks.

**Comment by Mister-Hope** [comment]
That's also something I am facing.

My workaround is to store pages one by one during each extendsPageData lifecycle. And visit the stored pages later

But I think it's better if the api can provide this feature.

**Comment by meteorlxy** [comment]
I'd ever considered whether to merge the previous extended data or not, but finally didn't implement that, because we currently don't have a `page.data` property in our page object.

But yes it would be helpful to make the merged page data available.

Need some refactor. We may need to move the `extendsPageData` hook to `init` stage, then the corresponding docs should also be updated (including the diagram about the hooks 😢 )
