### ISSUE TITLE
Dark mode flashed  on fisrt and next load.

### ISSUE THREAD

**Issue by wxsms** [vuepress/vuepress-next#387]
### Description

Firstly, thanks for the decent tool, helps a lot. But this problem is really annoying, and killing my eyes.

maybe this gif can be clear enough (the button I click means "refresh"):

![2](https://user-images.githubusercontent.com/5960988/129512599-60778ebd-94ba-42bb-8b2c-b635e4aed722.gif)

### Steps to reproduce

1. Set system to dark theme (win10 for me)
2. Open the document website, it flashed
3. Open it again or refresh, it flashed again

- Reproduction link / repo:

https://v2.vuepress.vuejs.org/

### Expected behavior

Darkmode should not flash, at least when I open it twice.

### Screenshots

provided gif above.

### Environment info

- Browser: Chrome
- Output of `vuepress info`: no need maybe? It can be reproduce with the official website.

------

A solution, maybe, we can simply remove the transition of the theme switching on page load, an it will become better?

**Comment by yinxulai** [comment]
I have the same problem

**Comment by domnantas** [comment]
I'm pretty sure this is caused by `backgroud-color` transition
https://github.com/vuepress/vuepress-next/blob/main/packages/@vuepress/theme-default/src/client/styles/normalize.scss#L6

**Comment by Danktuary** [comment]
For those curious, you can fix this by providing your own [`templateDev`](https://v2.vuepress.vuejs.org/reference/config.html#templatedev) and [`templateSSR`](https://v2.vuepress.vuejs.org/reference/config.html#templatessr) files.

`/docs/.vuepress/config.js`:

```js
const path = require('path');

module.exports = {
	templateDev: path.join(__dirname, 'templates', 'index.dev.html'),
	templateSSR: path.join(__dirname, 'templates', 'index.ssr.html'),
};
```

<details>
<summary><code>/docs/.vuepress/templates/index.dev.html</code>:</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<style>
		:root {
			--c-bg: #fff;
		}

		html.dark {
			--c-bg: #22272e;
		}

		html, body {
			background-color: var(--c-bg);
		}
	</style>
	<script>
		(function() {
			const userMode = localStorage.getItem('vuepress-color-scheme');
			const systemDarkMode = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;

			if (userMode === 'dark' || (userMode !== 'light' && systemDarkMode)) {
				document.documentElement.classList.toggle('dark', true);
			}
		})();
	</script>
</head>
<body>
	<div id="app"></div>
</body>
</html>
```

</details>

<details>
<summary><code>/docs/.vuepress/templates/index.ssr.html</code>:</summary>

```html
<!DOCTYPE html>
<html lang="{{ lang }}">
<head>
	<style>
		:root {
			--c-bg: #fff;
		}

		html.dark {
			--c-bg: #22272e;
		}

		html, body {
			background-color: var(--c-bg);
		}
	</style>
	<script>
		(function() {
			const userMode = localStorage.getItem('vuepress-color-scheme');
			const systemDarkMode = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;

			if (userMode === 'dark' || (userMode !== 'light' && systemDarkMode)) {
				document.documentElement.classList.toggle('dark', true);
			}
		})();
	</script>
<!--vuepress-ssr-head-->
<!--vuepress-ssr-resources-->
<!--vuepress-ssr-styles-->
</head>
<body>
	<div id="app"><!--vuepress-ssr-app--></div>
	<!--vuepress-ssr-scripts-->
</body>
</html>
```

</details>

Theme preferences are stored in `localStorage` as of `vuepress@^2.0-beta.24` (9582b3b72c42b28f74484b55d88bc1fb2d8f56df)

> I'm pretty sure this is caused by `backgroud-color` transition
> https://github.com/vuepress/vuepress-next/blob/main/packages/@vuepress/theme-default/src/client/styles/normalize.scss#L6

This is mainly caused by the [`useDarkMode()` composable](https://github.com/vuepress/vuepress-next/blob/main/packages/%40vuepress/theme-default/src/client/composables/useDarkMode.ts) handling the dark theme toggle, which is only called inside the [`ToggleDarkModeButton` component](https://github.com/vuepress/vuepress-next/blob/main/packages/%40vuepress/theme-default/src/client/components/ToggleDarkModeButton.vue) setup method. The `background-transition` property makes it apparent, but it still happens and is noticable without it.

**Comment by meteorlxy** [comment]
@Danktuary Yes, that's it.

Jest website does just the same thing:

https://jestjs.io/

**Comment by meteorlxy** [comment]
For now, theme could not do anything to the template. I'm considering to allow themes overriding default `templateDev` and `templateSSR` 🤔
