### ISSUE TITLE
[Feature request]Last update time Whether the time format can be customized

### ISSUE THREAD

**Issue by qcyblm** [vuepress/vuepress-next#431]
### Description

Time changed from 12 hours to 24 hours, etc

**Comment by DerZade** [comment]
Correct me if I'm wrong, but you are talking about this date?
![](https://i.imgur.com/dW6W2kB.png)


https://github.com/vuepress/vuepress-next/blob/a42e431a898240c67471a198fbde33c8805c2850/packages/%40vuepress/theme-default/src/client/components/PageMeta.vue#L101


Currently this uses `Date.toLocaleString` ([MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)) with the language from your config. So this format changes with the selected language.

**Comment by qcyblm** [comment]
VuePress v1 plugin @vuepress/plugin-last-updated
![图片](https://user-images.githubusercontent.com/64412486/132675514-2b422f2d-05a3-414c-acdb-c9d36eb5402a.png)

**Comment by Mister-Hope** [comment]
Not an issue here, the plugin is providing timestamp.

You probelm is probably that `theem-default` do not allow you to customize it.

Maybe you can extend this theme and support it yourself, not a hard work.

For me, I think the default behaviour should be ok in most situations.

**Comment by rol-peter** [comment]
> https://github.com/vuepress/vuepress-next/blob/a42e431a898240c67471a198fbde33c8805c2850/packages/%40vuepress/theme-default/src/client/components/PageMeta.vue#L101
> 
> Currently this uses `Date.toLocaleString` ([MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)) with the language from your config. So this format changes with the selected language.

`"language" != "locale"`. I'm from Sweden (we use 24 hour format and another date format), but I prefer using English because only 10 million speaks Swedish, and more than a billion speaks English. But I always have difficulties remembering which comes first of AM and PM, and if `8/9/2021` is Septemeber 8 or August 9. I.e. I know the language, but not the locale. Optimally locale should be whatever the browser's locale setting is set to (probably inherited from the OS)? Then everybody would get it in a format they recognize?

I agree that it's bad to make the locale customizeable, because then website creators can force a locale on the users, but this is basically what's going on now with the locale set to `siteLocale.value.lang`? I vote to use the browser's default locale instead (because web browsers do use the locale set in the OS? Does anyone know?).

**Comment by PeppeL-G** [comment]
> https://github.com/vuepress/vuepress-next/blob/a42e431a898240c67471a198fbde33c8805c2850/packages/%40vuepress/theme-default/src/client/components/PageMeta.vue#L101
> 
> Currently this uses `Date.toLocaleString` ([MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)) with the language from your config. So this format changes with the selected language.

`"language" != "locale"`. I'm from Sweden (we use 24 hour format and another date format), but I prefer using English because only 10 million speaks Swedish, and more than a billion speaks English. But I always have difficulties remembering which comes first of AM and PM, and if `8/9/2021` is Septemeber 8 or August 9. I.e. I know the language, but not the locale. Optimally locale should be whatever the browser's locale setting is set to (probably inherited from the OS)? Then everybody would get it in a format they recognize?

I agree that it's bad to make the locale customizeable, because then website creators can force a locale on the users, but this is basically what's going on now with the locale set to `siteLocale.value.lang`? I vote to use the browser's default locale instead (because web browsers do use the locale set in the OS? Does anyone know?).

**Comment by DerZade** [comment]
> `"language" != "locale"`. I'm from Sweden (we use 24 hour format and another date format), but I prefer using English because

You are absolutely right about that. I was just stating the current behavior. 

> (because web browsers do use the locale set in the OS? Does anyone know?).

Yes they do.

> Optimally locale should be whatever the browser's locale setting is set to (probably inherited from the OS)? Then everybody would get it in a format they recognize?

I totally agree. Just omitting the `siteLocale.value.lang` and calling `toLocaleString` without any parameters would be an easy change and would imho produce better results than the current behaviour.

**Comment by meteorlxy** [comment]
> Just omitting the siteLocale.value.lang and calling toLocaleString without any parameters would be an easy change and would imho produce better results than the current behaviour.

Not such easy change. It will cause SSR-mismatch problem:

- During SSR, `toLocaleString` will use the locale of your server where you build your site.
- During client hydration, `toLocaleString` will use the locale of the user's browser.

They are likely to be different, causing potential issue. So we also have to wrap it with `<ClientOnly>` to avoid that.

**Comment by qcyblm** [comment]
The last update time can be used to customize the time format using dateOptions.
Preview: https://qcyblm.gitee.io/vuepress-theme-vpx-next/guide/configs.html#dateoptions
