### ISSUE TITLE
[Bug report] page reload of URL having no hash specified sets wrong one

### ISSUE THREAD

**Issue by 185driver** [vuepress/vuepress-next#600]
### Description

By default, navigating to a URL via a navbar link results in no hash being applied (e.g. `https://v2.vuepress.vuejs.org/guide/`). This matches the expected behavior.

However, if the page is manually reloaded, two unexpected things happen:
1. The resultant URL now has a hash applied where none existed before
2. The hash that is applied is not the first item (e.g. `https://v2.vuepress.vuejs.org/guide/#introduction`). Instead, it is the second item (e.g. `https://v2.vuepress.vuejs.org/guide/#how-it-works`)

### Steps to reproduce

1. Navigate to[VuePress](https://v2.vuepress.vuejs.org/)
2. Click on the `Reference > CLI` navbar link
3. Click on the `Guide` navbar link and note the URL
4. Manually reload the page. Note the URL.

Reproduction link / repo:
The [VuePress](https://github.com/vuepress/vuepress-next/) repo itself.

### Expected behavior

Depending on the intended design of the project, a manual page reload would result in one of two possibilities as a default behavior:
1. No hash is applied to a 'bare' URL (preferred)
2. Apply the first item hash to the URL

### Environment info

- Browser: Chrome Windows 97.0.4692.56

### Additional observations
Clicking the `Guide` navbar link directly from the [home page](https://v2.vuepress.vuejs.org/) also yields this unexpected behavior.

Clicking away from the first item sidebar link to a child sidebar link and then back again to the first item sidebar link also yields unexpected behavior by appending the second item hash to the URL. However, if the first item sidebar link is then immediately clicked again, the hash is removed from the URL. 

These unexpected behaviors may be linked to the same root issue or they may be a separate issue to be resolved.

**Comment by meteorlxy** [comment]
It's supported by `@vuepress/plugin-active-header-links` with following config:

https://github.com/vuepress/vuepress-next/blob/16df99dd247a11eb68c7984dd16608e450f42eb0/packages/%40vuepress/plugin-active-header-links/src/node/activeHeaderLinksPlugin.ts#L13-L14

The "introduction" is the first `headerAnchor`, but it does not have a corresponding `headerLink`, so it won't be set as hash.

In other words, "how-it-works" is **the first** sidebar header link. So I'd say it's the current expected behavior.
