### ISSUE TITLE
[Feature request] Use better commitizen adapter <cz-git>

### ISSUE THREAD

**Issue by Zhengqbbb** [vuepress/vuepress-next#729]
### Description

**I open sourced a commitizen adapter [cz-git](https://github.com/Zhengqbbb/cz-git). It is perfect for projects using `monorepo project`**

- Supports search and selection on the command line, reducing spelling errors.
- Highly Customizable, but the output format follows the standard [Angular commit](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits) specification.
- [Better for monorepo engineering](https://github.com/Zhengqbbb/cz-git#scopes) and commitlint project to give relevant verification information to the command line.

![demo](https://user-images.githubusercontent.com/40693636/156009970-3eee46a5-ed17-49cf-9d3d-e4622ee10d3f.gif)

### Proposed Solution

If the manager dares to be interested, I am very willing to provide PR.
I'm more than willing to make adjustments if there are suggestions.

**Comment by Mister-Hope** [comment]
I am not sure about it, the tool is nice, but I am not seeing great benifit with it. You shall wait to see @meteorlxy 's opinion

The only thing the plugin provides is probably auto completing scope for this project (as we have long scopes). And that autocomplete based on input is nice.

> I'm more than willing to make adjustments if there are suggestions.

For the suggestions, IMO a such tool should be lightweight. I have a quick look at the lock file changes, and I found that your tool has more deps then I expected. So if there is any suggestions, (with your package rather than this PR), I would like to say maybe you can try to lower the deps number. And try require same versions of tools if possible.

**Comment by Zhengqbbb** [comment]
@Mister-Hope Thank Hope ! 
> (Maybe comming from `inquirer-autocomplete-prompt` I guess?)

Yeah. I use it.

> I would like to say maybe you can try to lower the deps number. And try require same versions of tools if possible.

Great suggestion. That will be my next feature ~
