### ISSUE TITLE
[Bug report]: `clean-cache` breaks the site (504 Gateway Timeout)

### ISSUE THREAD

**Issue by dacodekid** [vuepress/vuepress-next#800]
## Bug report
`vuepress dev --clean-cache` breaks the site by emitting `504 Gateway Timeout`

### Description
In `2.0.0-beta-38`, running `vuepress dev --clean-cache` stopped working.  It emits `504 Gateway Timeout` error messages (see screenshot) and produces a blank screen.  Restarting the server and removing `--clean-cache` works fine (`--clean-temp` seems working fine). 

### Screenshots
<img width="965" alt="image" src="https://user-images.githubusercontent.com/10047844/162167179-6ca4ab0d-50c0-447b-bd86-df256320208d.png">

### Environment info

- Browser:
```
    Chrome: 100.0.4896.75
    Edge: 100.0.1185.29
    Firefox: 98.0.2
    Safari: 15.4

```

- Output of `vuepress info`:
```
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.38 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.38 
    @vuepress/client:  2.0.0-beta.38 
    @vuepress/core:  2.0.0-beta.38 
    @vuepress/markdown:  2.0.0-beta.38 
    @vuepress/plugin-active-header-links:  2.0.0-beta.38 
    @vuepress/plugin-back-to-top:  2.0.0-beta.38 
    @vuepress/plugin-container:  2.0.0-beta.38 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.38 
    @vuepress/plugin-git:  2.0.0-beta.38 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.38 
    @vuepress/plugin-nprogress:  2.0.0-beta.38 
    @vuepress/plugin-palette:  2.0.0-beta.38 
    @vuepress/plugin-prismjs:  2.0.0-beta.38 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.38 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.38 
    @vuepress/theme-default:  2.0.0-beta.38 
    @vuepress/utils:  2.0.0-beta.38 
    vue:  3.2.31 
    vue-loader: Not Found
    vue-router:  4.0.14 
    vuepress: ^2.0.0-beta.38 => 2.0.0-beta.38 
    vuepress-vite:  2.0.0-beta.38 
    vuepress-webpack: Not Found

```

```bash
# Paste output of `vuepress info` here
```

**Comment by Mister-Hope** [comment]
Some details update:

chunks requesting by vite from brower side has hash, but the actual metadata.json (`.vuepress/.temp/_meta.json`) do not, so that when vite generate cache for the first time, all cache will be 504. Only if vite is restarted with an exisiting cache, can vite successfully request cache modules.

This could be caused by vite hash remove action used by `@vuepress/bundler-vite` as a workaround @meteorlxy .

---

## Possiable workaround:

1. run `vuepress dev xxx` or `vuepress dev xxx --clean-cache` first time, when you get 504 error with chunks, terminate that process
2. Rerun the same command WITHOUT `--clean-cache` flag to make sure using an exisiting cache this time, then everything will work fine.


---

## Related Info

This issue is still realted to an internal change breaking vuepress workaround in vite@2.9. You can revert to `vuepress@2.0.0-beta.37` to use vite@2.8 to avoid this problem.
